const sampleInsuranceLis = [
  {
    id: 1,
    providerName: 'AIA',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 3,
    providerName: 'Fidelity',
    username: '',
    password: '',
    isConnected: true,
  },
  {
    id: 4,
    providerName: 'Asteron Life',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 5,
    providerName: 'NIB',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 6,
    providerName: 'Partners Life',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 8,
    providerName: 'AMP',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 9,
    providerName: 'Cigna',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 10,
    providerName: 'Southern Cross',
    username: '',
    password: '',
    isConnected: false,
  },
  {
    id: 11,
    providerName: 'Accuro',
    username: '',
    password: '',
    isConnected: false,
  },
];
